name: Coverity

# Controls when the workflow will run
on:
  # Trigger the workflow based on cron.
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

# Workflow with 1 stage: Build.
# Each of the sub-stages in the build job run in parallel.
jobs:
  build:

    # Use the latest ubuntu image: https://github.com/actions/runner-images
    runs-on: ubuntu-24.04
    name: LArContent - Coverity

    # Only run in the PandoraPFA repos.
    if: github.repository_owner == 'PandoraPFA'

    # Defines the build matrix, so what combinatorics of compiler etc. to test.
    strategy:
      fail-fast: false # Don't quit other jobs if one job fails.
      matrix:
        compiler: [ {cpp: g++-12, c: gcc-12} ]
        monitoring: [ "ON" ]
        torch: [ "ON" ]

    # Set the compiler env vars to ensure the correct compiler is used.
    env:
        CC: ${{ matrix.compiler.c }}
        CXX: ${{ matrix.compiler.cpp }}

    steps:

      - name: Checkout Workflow Repository
        uses: actions/checkout@v5

      - name: Setup Pandora Build Dependencies
        uses: ./.github/actions/pandora-setup
        with:
          monitoring: ${{ matrix.monitoring }}
          torch: ${{ matrix.torch }}

      # Cache the build tool, to speed up subsequent runs.
      - name: Cache Coverity Build Tool
        id: cov-build-cache
        uses: actions/cache@v4
        with:
          path: /pandora/coverity/
          key: cov-build-2023.12

      # Get Coverity build tool
      - name: Get Coverity Build Tool
        if: steps.cov-build-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p /pandora/coverity/ && cd /pandora/coverity/
          curl https://scan.coverity.com/download/cxx/linux64/ \
            --no-progress-meter \
            --output cov-analysis.tar.gz \
            --data "token=${{ secrets.COVERITY_SCAN_TOKEN }}&project=${{ secrets.COVERITY_REPO }}"
          mkdir cov-analysis
          tar -zxf cov-analysis.tar.gz --strip 1 -C cov-analysis
          pwd
          ls
          ls *
          rm cov-analysis.tar.gz
          export PATH="${PWD}/cov-analysis/bin:${PATH}"
          cov-configure -co $(which ${CXX}) -- -std=c++17 -fPIC

      - name: Setup Pandora Build Dependencies
        uses: ./.github/actions/pandora-setup
        with:
          monitoring: ${{ matrix.monitoring }}
          torch: ${{ matrix.torch }}
          larcontent_repository: PandoraPFA/LArContent

      - name: Build Pandora Stack
        uses: ./.github/actions/pandora-build
        with:
          monitoring: ${{ matrix.monitoring }}
          torch: ${{ matrix.torch }}
          build_larreco: "false"
          larcontent_build_mode: coverity

      - name: Upload to Coverity
        run: |
          cd /pandora/LArContent/build
          curl \
            --form token="${{ secrets.COVERITY_SCAN_TOKEN }}" \
            --form email="${{ secrets.COVERITY_EMAIL }}" \
            --form file=@coverity_build.tar.gz \
            --form version="${{ github.sha }}" \
            --form description="$(date)" \
            "https://scan.coverity.com/builds?project=${{ secrets.COVERITY_REPO }}"
