name: Build LArContent

# Controls when the workflow will run
on:
  # Trigger the workflow on push to master, or any pull request.
  # workflow_dispatch allows manual running through the GitHub UI.
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

# Workflow with 1 stage: Build.
# Each of the sub-stages in the build job run in parallel.
jobs:
  build:

    # Use the latest ubuntu image: https://github.com/actions/runner-images
    runs-on: ubuntu-24.04
    name: LArContent - ${{ matrix.compiler.c }} - Monitoring ${{ matrix.monitoring }} - DL ${{ matrix.torch }}

    # Only run in the PandoraPFA repos.
    if: github.repository_owner == 'PandoraPFA'

    # Defines the build matrix, so what combinatorics of compiler etc. to test.
    strategy:
      fail-fast: false # Don't quit other jobs if one job fails.
      matrix:
        compiler: [ {cpp: g++-12, c: gcc-12}, {cpp: clang++, c: clang} ]
        monitoring: [ "ON", "OFF" ]
        torch: [ "ON", "OFF" ]

    # Set the compiler env vars to ensure the correct compiler is used.
    env:
        CC: ${{ matrix.compiler.c }}
        CXX: ${{ matrix.compiler.cpp }}

    steps:

      - name: Checkout Workflow Repository
        uses: actions/checkout@v5

      - name: Setup Pandora Build Dependencies
        uses: ./.github/actions/pandora-setup
        with:
          monitoring: ${{ matrix.monitoring }}
          torch: ${{ matrix.torch }}

      - name: Build Pandora Stack
        uses: ./.github/actions/pandora-build
        with:
          monitoring: ${{ matrix.monitoring }}
          torch: ${{ matrix.torch }}
